name: CMake Build and Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          ninja-build \
          pkg-config \
          libssl-dev \
          libwebsockets-dev \
          libcjson-dev \
          libavahi-compat-libdnssd-dev

    - name: Configure CMake
      run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: Build
      run: cmake --build build --config ${{ env.BUILD_TYPE }}

    - name: Configure unit tests
      run: cmake -B tests/build -S tests -G Ninja -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: Build unit tests
      run: cmake --build tests/build --config ${{ env.BUILD_TYPE }}

    - name: Run unit tests
      run: ctest --test-dir tests/build -C ${{ env.BUILD_TYPE }} --output-on-failure
